### ISSUE TITLE
You might want to provide more documentation.

### ISSUE THREAD

**Issue by Wikileas** [chaarlottte/capsolver-generator-checker#2]
Took me a while to find where to install charlogger, as using pip wasn't working, due to some setup.py thing.

When installed:
`root@vm:~/capsolver-generator-checker# python3 main.py
Traceback (most recent call last):
  File "/root/capsolver-generator-checker/main.py", line 1, in <module>
    from src.task import CapsolverGen, CapsolverChecker
  File "/root/capsolver-generator-checker/src/task/__init__.py", line 1, in <module>
    from .checker import CapsolverChecker
  File "/root/capsolver-generator-checker/src/task/checker.py", line 2, in <module>
    from ..util.config import Config
  File "/root/capsolver-generator-checker/src/util/config.py", line 3, in <module>
    class Config():
  File "/root/capsolver-generator-checker/src/util/config.py", line 25, in Config
    def getLogger(self, workerNum: str) -> charlogger.Logger:
AttributeError: module 'charlogger' has no attribute 'Logger`

Do not know if this is something that happened because of the installation, but can't really work.

**Comment by laika-cosmonaut** [comment]
pip uninstall charlogger
pip install charlogger
